### PR TITLE
Add Mange's CV using submodule + fix Makefile

### PR DESCRIPTION
**Pull request by Mange**
Since the CV is already maintained in another repo, this removes the need for us to duplicate the text and template for it.

Also fixed the `Makefile` so it doesn't always rebuild the other files.

### CODE REVIEW

**Review by meric426 — APPROVED** [review]
Very tasty 👍 

@jonlil should probably do the same

**Comment by stefanahman** [comment]
The idea of collecting the CV:s here is to use the same template for all developers. There could be a difference in your personal resume and Devbox resume.

**Comment by Mange** [comment]
> The idea of collecting the CV:s here is to use the same template for all developers.

But it also means that we'd have to keep two CVs in sync. I think that would be more annoying.
If I make changes to the template we could port the same change over here as well, just like we did when we originally moved to using my CV as a template for the others. :-)

**Comment by meric426** [comment]
I think linking your CV with this repo using a submodule is a good solution. They all use the same template right now but might and probably will diverge in the future when we add more developers

**Comment by stefanahman** [comment]
I think there is (could be) a difference between a personal CV and a consultant CV. Also, in the future each profile could have multiple CVs for different assignments. But lets keep the submodule for now and have a chat later when that day comes

**Review by stefanahman — APPROVED** [review]

**Pull request merged**
